Fix/pr changes
JortWillemsen/stryker-dashboard-redesign pull request #20
Opened 2023-10-19 14:24 UTC by JortWillemsen

Some fixes for easy changes requested for the PR with stryker-dashboard.

I did not really look for formatting since we probably need to do that all at once when all other changes are completed.

2023-10-19 17:59 UTC, xandervedder commented on packages/ui-components/src/components/hero-component.ts
> +              >
Not necessarily for this PR, but I really don't like this formatting... 🙃

2023-10-19 18:00 UTC, xandervedder commented on packages/ui-components/src/components/hero-component.ts
> +              >
I guess increasing the width to something higher than 80 (?) would probably suffice, but we can do that later (in the actual repository).

2023-10-19 18:01 UTC, xandervedder requested changes

2023-10-19 18:01 UTC, xandervedder commented on packages/ui-components/src/components/top-bar.ts
>      }
Remove this method as it's not being used anymore.

2023-10-19 20:03 UTC, jensk-dev commented on packages/ui-components/src/components/top-bar.ts
> +      ${this.logo && html`<img class="p-2 h-12" src="${this.logo}" />`}
You could consider using lit's [`nothing`](https://lit.dev/docs/templates/conditionals/#conditionally-rendering-nothing) sentinel value, here.

```suggestion
      ${!!this.logo ? html`<img class="p-2 h-12" src="${this.logo}" />` : nothing}
```

2023-10-21 10:15 UTC, xandervedder commented on packages/ui-components/src/components/top-bar.ts
> +      ${this.logo && html`<img class="p-2 h-12" src="${this.logo}" />`}
I would personally only do this if the check gets more complex. For example actually check if the logo is an empty string. Stuff like that.

2023-10-21 10:30 UTC, xandervedder approved these changes

2023-10-21 10:30 UTC, merged